
# ___ Generated by AutoUWP Launcher v1.1.0 (c) 2018-2019, SalFisher47
#     Loosely based on .ps1 scripts by prudislav & pakrat2k2 @ fileforums.com

# ---> '.\AppxManifest.xml'
Write-Host "   "
Write-Host -ForegroundColor Yellow "   *** AutoUWP Launcher v1.1.0 (c) 2018-2019, SalFisher47 ***"
Write-Host "   "
Write-Host -ForegroundColor Cyan "   *** AutoUWP Launcher ... uninstalling UWP game ***"
Write-Host "   "
$xmlPath = [String]$pwd +  '\AppxManifest.xml'
$xml = [xml](Get-Content $xmlPath -ErrorAction SilentlyContinue) 
if(Test-Path $xmlPath){
    Write-Host -ForegroundColor Green "   .\AppxManifest.xml found!"
    Write-Host -ForegroundColor Green "      $xmlPath"
    Write-Host "   "
    $AppId = $xml.Package.Applications.Application.ID
    $AppName =  $xml.Package.Identity.Name
    $FamName = get-appxpackage $AppName | Select PackageFamilyName
    $FullName = get-appxpackage $AppName | Select PackageFullName
    $GameName = $xml.Package.Properties.DisplayName
    if($FamName){
        Write-Host -ForegroundColor Green "   uninstalling game ---> "
        Write-Host -ForegroundColor Green "      $GameName ($AppName) ... "
        Get-AppxPackage $AppName | Remove-AppxPackage
        $FamName = get-appxpackage $AppName | Select PackageFamilyName
        if(!$FamName){
            Write-Host -ForegroundColor Green "         $GameName IS NOT INSTALLED"
            Write-Host "   "
            }
        else{
            Write-Host -ForegroundColor Red "         $GameName IS INSTALLED"
            Write-Host "   "
            }
        #Pause
        #Exit
        }
    else{
        $FamName = $FamName.PackageFamilyName
        $param = $FamName + '!' + $AppId
        Write-Host -ForegroundColor Green "   uninstalling game ---> "
        Write-Host -ForegroundColor Green "      $GameName ($AppName) ... "
        Write-Host -ForegroundColor Green "         $GameName IS NOT INSTALLED"
        Write-Host "   "
        #Pause
        #Exit
        }
    }
 else{
    Write-Host -ForegroundColor Red '   .\AppxManifest.xml not found!'
    Write-Host -ForegroundColor Red '   Make sure autoUWP launcher is next to .\AppFiles folder!'
    #Pause
    #Exit
    }
# <--- '.\AppxManifest.xml'
